name: 'serverless-with-python-requirements'
description: 'An action to deploy serverless projects made in python'

inputs:
  args:
    default: ''
    description: 'Additional arguments you want to set'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}

branding:
  icon: 'upload-cloud'
  color: 'orange'
