on: [ push ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: bildvitta/serverless-with-python-requirements@master
        with:
          args: '--stage dev'
        env:
          AWS_ACCESS_KEY_ID: "12345679"
          AWS_SECRET_ACCESS_KEY: "987654321"
